# Generated by Django 4.1.7 on 2023-03-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0002_model2_alter_model1_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model2',
            name='pole3',
        ),
        migrations.AddField(
            model_name='model1',
            name='pole3',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
